services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "dev"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

volumes:
  postgres-vol:
    
networks: 
  postgres-compose-network:
    driver: bridge